version: '3.8'

services:
  user_service:
    build: ./services/user_service
    ports:
      - '5001:5001'
      - '8000:8000'
    networks:
      - efk
    platform: linux/arm64

  order_service:
    build: ./services/order_service
    ports:
      - "5002:5002"
      - "8001:8001"
    networks:
      - efk
    platform: linux/arm64
  
  dashboard:
    build: ./dashboard
    ports:
      - "8080:8080"
    networks:
      - efk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - efk
    platform: linux/arm64 

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk
    platform: linux/amd64
    depends_on:
      - elasticsearch
      - kibana

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - efk

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - efk
    platform: linux/arm64
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=im15im15

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - efk
    platform: linux/arm64

networks:
  efk:
    driver: bridge