global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:5001']
  - job_name: 'user_service_metrics'
    static_configs:
      - targets: ['user_service:8000']